openapi: 3.0.0
info:
  title: Bookstore Inventory Management API
  version: 1.0.0
  description: API for managing books and their stock information
servers:
  - url: http://localhost:8000
paths:
  /books:
    get:
      summary: List all books
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Book'
    post:
      summary: Create a new book
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookCreate'
      responses:
        '201':
          description: Book created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /books/{id}:
    get:
      summary: Get a specific book
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'

  /book-stocks:
    get:
      summary: List all book stocks
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BookStock'
    post:
      summary: Create a new book stock entry
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BookStockCreate'
      responses:
        '201':
          description: Book stock created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookStock'

  /book-stocks/{id}:
    get:
      summary: Get a specific book stock
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BookStock'

components:
  schemas:
    Book:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        isbn:
          type: string
      required:
        - id
        - name
        - isbn

    BookCreate:
      type: object
      properties:
        name:
          type: string
        isbn:
          type: string
      required:
        - name
        - isbn

    BookStock:
      type: object
      properties:
        id:
          type: integer
        book_id:
          type: integer
      required:
        - id
        - book_id

    BookStockCreate:
      type: object
      properties:
        book_id:
          type: integer
      required:
        - book_id
